DROP TABLE BANKUSER CASCADE CONSTRAINTS;
CREATE TABLE BANKUSER 
   ("BANKUID" NUMBER, 
	"USERNAME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"PASSWD" VARCHAR2(256 BYTE), 
	 PRIMARY KEY ("BANKUID")
   );
   
CREATE OR REPLACE PROCEDURE new_user   
(   neo_uid IN BANKUSER.BANKUID%TYPE,
    neo_name IN BANKUSER.USERNAME%TYPE,
	neo_password IN BANKUSER.PASSWD%TYPE
)
IS
BEGIN
    INSERT INTO BANKUSER(BANKUID, USERNAME, PASSWD) VALUES (neo_uid, neo_name, neo_password);
END;
/

BEGIN 
  new_user(0, 'BigMoney', '$2a$10$hwLbjzKYDVaZDJHma1ioee8NkLbLnhF0tlnNo/r5GmbWyi2QpOQw6');
END;
/
 
DROP TABLE PERMISSION CASCADE CONSTRAINTS;
CREATE TABLE PERMISSION 
   (	PERMISSION NUMBER PRIMARY KEY
   );
  INSERT INTO PERMISSION VALUES (0);
  INSERT INTO PERMISSION VALUES (1);
  
DROP TABLE USER_PERMISSION CASCADE CONSTRAINTS;
CREATE TABLE USER_PERMISSION   
  (	
     BANKUID NUMBER NOT NULL, 
	 PERMISSION NUMBER NOT NULL, 
	 PRIMARY KEY ("BANKUID", "PERMISSION"),
	 FOREIGN KEY ("BANKUID")
	  REFERENCES BANKUSER("BANKUID"), 
	 FOREIGN KEY ("PERMISSION")
	  REFERENCES PERMISSION ("PERMISSION") 
  );

DROP TABLE BANKACCOUNTTYPE CASCADE CONSTRAINTS;
CREATE TABLE BANKACCOUNTTYPE 
   (	"ACCOUNTTYPE" VARCHAR2(40 BYTE) PRIMARY KEY, 
        "BANKUID"     NUMBER UNIQUE NOT NULL
   );
INSERT INTO BANKACCOUNTTYPE (ACCOUNTTYPE, BANKUID) VALUES ('ACCT_CHECK', 1);
INSERT INTO BANKACCOUNTTYPE (ACCOUNTTYPE, BANKUID) VALUES ('ACCT_SAVE', 0);
INSERT INTO BANKACCOUNTTYPE (ACCOUNTTYPE, BANKUID) VALUES ('APPLY_CHECK', 2);
INSERT INTO BANKACCOUNTTYPE (ACCOUNTTYPE, BANKUID) VALUES ('APPLY_SAVE', 3);
INSERT INTO BANKACCOUNTTYPE (ACCOUNTTYPE, BANKUID) VALUES ('DENIED', 4);
INSERT INTO BANKACCOUNTTYPE (ACCOUNTTYPE, BANKUID) VALUES ('CANCEL', 5);

DROP TABLE BANKACCOUNT CASCADE CONSTRAINTS;
CREATE TABLE BANKACCOUNT 
   (	"BANKUID" NUMBER PRIMARY KEY, 
	"ACCTTYPE" NUMBER DEFAULT 0, 
	"AMOUNT" NUMBER CHECK (AMOUNT >= 0),
	FOREIGN KEY ("ACCTTYPE")
	  REFERENCES BANKACCOUNTTYPE (BANKUID)
	);
INSERT INTO BANKACCOUNT VALUES (0, 1, 250);	
INSERT INTO BANKACCOUNT VALUES (1, 0, 50);	
	
CREATE OR REPLACE PROCEDURE xfer_funds(
    source_acct IN NUMBER, dest_acct IN NUMBER, t_amount IN NUMBER
)	
IS
  source_bal NUMBER;
  dest_bal NUMBER;
BEGIN
  --DBMS_OUTPUT.ENABLE;
  --DBMS_OUTPUT.PUT_LINE('We exist.');
  SELECT (ba.amount) INTO source_bal FROM BANKACCOUNT ba WHERE ba.bankuid = source_acct;
  source_bal := source_bal - t_amount;
  --DBMS_OUTPUT.PUT_LINE(1 || ' ' ||source_bal || ' ' || dest_bal);
  UPDATE BANKACCOUNT SET AMOUNT = source_bal WHERE BANKUID = source_acct;
  --DBMS_OUTPUT.PUT_LINE(source_bal || ' ' || dest_bal);
  SELECT (ba.amount) INTO dest_bal FROM BANKACCOUNT ba WHERE ba.bankuid = dest_acct;
  dest_bal := dest_bal + t_amount;
  --DBMS_OUTPUT.PUT_LINE(source_bal || ' ' || dest_bal);
  UPDATE BANKACCOUNT SET AMOUNT = dest_bal WHERE BANKUID = dest_acct;
  COMMIT;
  --DBMS_OUTPUT.PUT_LINE(source_bal || ' ' || dest_bal);
END;
/

BEGIN 
  xfer_funds(0, 1, 10);
END;
/
  
DROP TABLE USER_ACCOUNT CASCADE CONSTRAINTS;
CREATE TABLE USER_ACCOUNT 
   (	"USERUID" NUMBER, 
	"ACCTUID" NUMBER, 
	 PRIMARY KEY ("USERUID", "ACCTUID"),
	 FOREIGN KEY ("USERUID")
	  REFERENCES BANKUSER ("BANKUID"), 
	 FOREIGN KEY ("ACCTUID")
	  REFERENCES BANKACCOUNT ("BANKUID")
   );
  
DROP TABLE TRANSTYPE CASCADE CONSTRAINTS;
CREATE TABLE TRANSTYPE 
   (	"TRANSTYPE" VARCHAR2(40 BYTE) PRIMARY KEY, 
		"TRANSID"   NUMBER NOT NULL
	);
INSERT INTO "TRANSTYPE" VALUES('TRANS_DEPOSIT', 1);
INSERT INTO "TRANSTYPE" VALUES('TRANS_WITHDRAW', 0);


DROP TABLE "BANKTRANS" CASCADE CONSTRAINTS;
CREATE TABLE "BANKTRANS" 
   (	"TRANSUID" NUMBER PRIMARY KEY, 
	"USERUID" NUMBER NOT NULL, 
	"ACCOUNTUID" NUMBER NOT NULL, 
	"TRANSTYPE" NUMBER NOT NULL, 
	"AMOUNT" FLOAT(126), 
	"TRANSDAY" DATE, 
	"TRANSTIME" TIMESTAMP (6) WITH TIME ZONE
	);
	
DROP TABLE ADDRESS CASCADE CONSTRAINTS;
CREATE TABLE ADDRESS (
  BANKUID NUMBER PRIMARY KEY,
  STREET1 VARCHAR2(40),
  STREET2 VARCHAR2(40),
  CITY    VARCHAR2(40),
  STATE   VARCHAR2(2),
  ZIP     NUMBER
);
INSERT INTO ADDRESS VALUES (0,'1 Big Money Blvd', 'Suite 100',
    'New York City', 'NY', 10006);

DROP TABLE USER_ADDRESS CASCADE CONSTRAINTS;
CREATE TABLE USER_ADDRESS (
    "USERUID" NUMBER, 
	"ADDRUID" NUMBER, 
	 PRIMARY KEY ("USERUID", "ADDRUID"),
	 FOREIGN KEY ("USERUID")
	  REFERENCES BANKUSER ("BANKUID"), 
	 FOREIGN KEY ("ADDRUID")
	  REFERENCES ADDRESS ("BANKUID")
);
INSERT INTO USER_ADDRESS VALUES (0, 0);