sudo: required
dist: focal
language: node_js
branches:
  only:
    - main
    - develop
node_js:
  - 12.16.*
cache:
  - pip
  - npm
install:
  - pip install --user awscli
before_script:
  - npm ci
script: ./travis/build.sh
deploy:
  - provider: script
    script: ./travis/deploy.sh
    skip_cleanup: true
    on:
      repo: sendgrid/docs
      all_branches: true
      condition: $TRAVIS_BRANCH = develop || $TRAVIS_BRANCH = main
  - provider: script
    script: ./travis/deploy_open_source.sh
    skip_cleanup: true
    on:
      repo: sendgrid/docs
      all_branches: true
      condition: $TRAVIS_BRANCH = develop
after_deploy: ./travis/after_deploy.sh
