CREATE USER ERS_EMERALD IDENTIFIED BY Emerald4Boss;
GRANT CREATE SESSION TO ERS_EMERALD;
GRANT UNLIMITED TABLESPACE TO ERS_EMERALD;
GRANT CREATE TABLE TO ERS_EMERALD;
GRANT CREATE VIEW TO ERS_EMERALD;
GRANT CREATE SEQUENCE TO ERS_EMERALD;
GRANT CREATE TRIGGER TO ERS_EMERALD;
GRANT CREATE PROCEDURE TO ERS_EMERALD;

DROP TABLE ERS_USER_ROLES CASCADE CONSTRAINTS;
CREATE TABLE ERS_USER_ROLES (
  ERS_USER_ROLE_ID  NUMBER,
  USER_ROLE         VARCHAR2(10),
  CONSTRAINT ers_user_roles_pk PRIMARY KEY (ERS_USER_ROLE_ID)
);
INSERT INTO ERS_USER_ROLES VALUES (0, 'CUSTOMER');
INSERT INTO ERS_USER_ROLES VALUES (1, 'FIN ADMIN');

DROP TABLE ERS_REIMBURSEMENT_TYPE CASCADE CONSTRAINTS;
CREATE TABLE ERS_REIMBURSEMENT_TYPE (
  REIMB_TYPE_ID  NUMBER,
  REIMB_TYPE     VARCHAR2(10),
  CONSTRAINT reimb_type_pk PRIMARY KEY (REIMB_TYPE_ID)
);
INSERT INTO ERS_REIMBURSEMENT_TYPE VALUES (0, 'OTHER');
INSERT INTO ERS_REIMBURSEMENT_TYPE VALUES (1, 'LODGING');
INSERT INTO ERS_REIMBURSEMENT_TYPE VALUES (2, 'TRAVEL');
INSERT INTO ERS_REIMBURSEMENT_TYPE VALUES (3, 'FOOD');

DROP TABLE ERS_REIMBURSEMENT_STATUS CASCADE CONSTRAINTS;
CREATE TABLE ERS_REIMBURSEMENT_STATUS (
  REIMB_STATUS_ID  NUMBER,
  REIMB_TYPE       VARCHAR2(10),
  CONSTRAINT reimb_type_pd PRIMARY KEY (REIMB_STATUS_ID)
);
INSERT INTO ERS_REIMBURSEMENT_STATUS VALUES (0, 'DENIED');
INSERT INTO ERS_REIMBURSEMENT_STATUS VALUES (1, 'PENDING');
INSERT INTO ERS_REIMBURSEMENT_STATUS VALUES (2, 'APPROVED');

DROP TABLE ERS_USERS CASCADE CONSTRAINTS;
CREATE TABLE ERS_USERS (
  ERS_USERS_ID     NUMBER,
  ERS_USERNAME     VARCHAR2(50) UNIQUE,
  ERS_PASSWORD     VARCHAR2(70),
  USER_FIRST_NAME  VARCHAR2(100),
  USER_LAST_NAME   VARCHAR2(100),
  USER_EMAIL       VARCHAR2(150) UNIQUE,
  USER_ROLE_ID     NUMBER,
  UNIQUE (ERS_USERNAME, USER_EMAIL),
  CONSTRAINT ers_users_pk PRIMARY KEY (ERS_USERS_ID),
  CONSTRAINT user_roles_fk FOREIGN KEY (USER_ROLE_ID) REFERENCES ERS_USER_ROLES(ERS_USER_ROLE_ID) 
);

DROP TABLE ERS_REIMBURSEMENT CASCADE CONSTRAINTS;
CREATE TABLE ERS_REIMBURSEMENT (
  REIMB_ID          NUMBER PRIMARY KEY,
  REIMB_AMOUNT      NUMBER,
  REIMB_SUBMITTED   TIMESTAMP,
  REIMB_RESOLVED    TIMESTAMP,
  REIMB_DESCRIPTION VARCHAR2(250),
  REIMB_RECEIPT     BLOB,
  REIMB_AUTHOR      NUMBER,
  REIMB_RESOLVER    NUMBER,
  REIMB_STATUS_ID   NUMBER,
  REIMB_TYPE_ID     NUMBER,
  CONSTRAINT  ers_users_fk_auth FOREIGN KEY (REIMB_AUTHOR) REFERENCES ERS_USERS(ERS_USERS_ID),
  CONSTRAINT ers_users_fk_reslvr FOREIGN KEY (REIMB_RESOLVER) REFERENCES ERS_USERS(ERS_USERS_ID),
  CONSTRAINT ers_reimbursement_status_fk FOREIGN KEY (REIMB_STATUS_ID) REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),
  CONSTRAINT ers_reimbursement_type_fk FOREIGN KEY (REIMB_TYPE_ID) REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)
);